# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mem.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(754, 729)
        # self.log = QtWidgets.QTextEdit(Dialog)
        # self.log.setGeometry(QtCore.QRect(40, 150, 251, 441))
        # self.log.setReadOnly(True)
        # self.log.setObjectName("log")
        self.res = QtWidgets.QTextEdit(Dialog)
        self.res.setGeometry(QtCore.QRect(330, 150, 241, 441))
        self.res.setReadOnly(True)
        self.res.setObjectName("res")
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(70, 40, 468, 100))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.select1 = QtWidgets.QComboBox(self.widget)
        self.select1.setObjectName("select1")
        self.select1.addItem("")
        self.select1.addItem("")
        self.gridLayout.addWidget(self.select1, 0, 2, 1, 1)
        self.select2 = QtWidgets.QComboBox(self.widget)
        self.select2.setObjectName("select2")
        self.select2.addItem("")
        self.select2.addItem("")
        self.select2.addItem("")
        self.select2.addItem("")
        self.gridLayout.addWidget(self.select2, 0, 3, 1, 1)
        self.select3 = QtWidgets.QLineEdit(self.widget)
        self.select3.setObjectName("select3")
        self.gridLayout.addWidget(self.select3, 0, 4, 1, 1)
        self.selectb = QtWidgets.QPushButton(self.widget)
        self.selectb.setObjectName("selectb")
        self.gridLayout.addWidget(self.selectb, 0, 5, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 2)
        self.project1 = QtWidgets.QComboBox(self.widget)
        self.project1.setObjectName("project1")
        self.project1.addItem("")
        self.project1.addItem("")
        self.gridLayout.addWidget(self.project1, 1, 2, 1, 1)
        self.project2 = QtWidgets.QComboBox(self.widget)
        self.project2.setObjectName("project2")
        self.project2.addItem("")
        self.project2.addItem("")
        self.project2.addItem("")
        self.project2.addItem("")
        self.gridLayout.addWidget(self.project2, 1, 3, 1, 1)
        self.projectb = QtWidgets.QPushButton(self.widget)
        self.projectb.setObjectName("projectb")
        self.projectc = QtWidgets.QPushButton(self.widget)
        self.projectc.setObjectName("projectc")
        self.gridLayout.addWidget(self.projectb, 1, 4, 1, 1)
        self.gridLayout.addWidget(self.projectc, 2, 3, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.save = QtWidgets.QPushButton(self.widget)
        self.save.setObjectName("save")
        self.gridLayout.addWidget(self.save, 2, 5, 1, 1)
        self.join1 = QtWidgets.QComboBox(self.widget)
        self.join1.setObjectName("join1")
        self.join1.addItem("")
        self.join1.addItem("")
        self.join1.addItem("")
        self.gridLayout.addWidget(self.join1, 2, 4, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
#         self.log.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
# "<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
# "p, li { white-space: pre-wrap; }\n"
# "</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
# "<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\">操作过程</span></p>\n"
# "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p>\n"
# "<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-family:\'MS Shell Dlg 2\'; font-size:8.25pt;\"><br /></p></body></html>"))
        self.res.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'SimSun\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">result</p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.label.setText(_translate("Dialog", "选择"))
        self.select1.setItemText(0, _translate("Dialog", "R"))
        self.select1.setItemText(1, _translate("Dialog", "S"))
        self.select2.setItemText(0, _translate("Dialog", "A"))
        self.select2.setItemText(1, _translate("Dialog", "B"))
        self.select2.setItemText(2, _translate("Dialog", "C"))
        self.select2.setItemText(3, _translate("Dialog", "D"))
        self.select3.setText(_translate("Dialog", "40"))
        self.selectb.setText(_translate("Dialog", "执行"))
        self.label_2.setText(_translate("Dialog", "投影"))
        self.project1.setItemText(0, _translate("Dialog", "R"))
        self.project1.setItemText(1, _translate("Dialog", "S"))
        self.project2.setItemText(0, _translate("Dialog", "A"))
        self.project2.setItemText(1, _translate("Dialog", "B"))
        self.project2.setItemText(2, _translate("Dialog", "C"))
        self.project2.setItemText(3, _translate("Dialog", "D"))
        self.projectb.setText(_translate("Dialog", "执行"))
        self.projectc.setText(_translate("Dialog", "执行"))
        self.label_3.setText(_translate("Dialog", "连接"))
        self.save.setText(_translate("Dialog", "结果保存"))
        self.join1.setItemText(0, _translate("Dialog", "nlj"))
        self.join1.setItemText(1, _translate("Dialog", "hash_join"))
        self.join1.setItemText(2, _translate("Dialog", "sort_merge_join"))
