# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'op.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you   know what you are doing.


from PyQt5 import QtCore,  QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(780, 563)
        # self.lineEdit = QtWidgets.QLineEdit(Dialog)
        # self.lineEdit.setGeometry(QtCore.QRect(30, 80, 721, 41))
        # self.lineEdit.setObjectName("lineEdit")
        self.select = QtWidgets.QComboBox(Dialog)
        self.select.setGeometry(QtCore.QRect(30, 30, 721, 41))
        self.select.setObjectName("select")
        self.select.addItem("")
        self.select.addItem("")
        self.select.addItem("")
      #  self.select.addItem("")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(190, 140, 321, 381))
        self.textEdit.setObjectName("textEdit")
        # self.show = QtWidgets.QPushButton(Dialog)
        # self.show.setGeometry(QtCore.QRect(590, 170, 93, 28))
        # self.show.setObjectName("show")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(590, 210, 93, 28))
        self.pushButton_2.setObjectName("pushButton_2")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.select.setItemText(0, _translate("Dialog", "SELECT [ ENAME = ’Mary’ & DNAME = ’Research’ ] ( EMPLOYEE JOIN DEPARTMENT )"))
        self.select.setItemText(1, _translate("Dialog", "PROJECTION [ BDATE ] ( SELECT [ ENAME = ’John’ & DNAME = ’ Research’ ] ( EMPLOYEE JOIN DEPARTMENT) )"))
        self.select.setItemText(2, _translate("Dialog", "SELECT [ ESSN = ’01’ ] (  PROJECTION [ ESSN, PNAME ] ( WORKS_ON JOIN PROJECT ) )"))
       # self.select.setItemText(2, _translate("Dialog", "PROJECTION [ DNAME, SALARY ] ( AVG [ SALARY ] ( SELECT [ DNAME = ’ Research’ ] ( EMPLOYEE  JOIN  DEPART MENT) )"))

        #self.show.setText(_translate("Dialog", "显示"))
        self.pushButton_2.setText(_translate("Dialog", "查询优化"))
